apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      component: airflow-webserver
  template:
    metadata:
      labels:
        component: airflow-webserver
    spec:
      containers:
      - name: airflow-webserver
        image: furnar000/airflow
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: airflow-config
        - secretRef:
            name: airflow-secrets
        env:
          - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
            value: "postgresql+psycopg2://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres/airflow"
          - name: AIRFLOW__CELERY__RESULT_BACKEND
            value: "db+postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres/airflow"
        command: [ "airflow" ]
        args: [ "webserver" ]
        volumeMounts:
        - name: dags
          mountPath: /opt/airflow/dags
        - name: logs
          mountPath: /opt/airflow/logs
        - name: plugins
          mountPath: /opt/airflow/plugins
        - name: src
          mountPath: /opt/airflow/src
      volumes:
      - name: dags
        persistentVolumeClaim:
          claimName: airflow-dags-pvc
      - name: logs
        persistentVolumeClaim:
          claimName: airflow-logs-pvc
      - name: plugins
        persistentVolumeClaim:
          claimName: airflow-plugins-pvc
      - name: src
        persistentVolumeClaim:
          claimName: airflow-src-pvc
